export const LOGIN = 'mg/LOGIN';
export const LOGIN_SUCCESS = 'mg/LOGIN_SUCCESS';
export const LOGIN_ERROR = 'mg/LOGIN_ERROR';

export const REGISTER = 'mg/REGISTER';
export const REGISTER_SUCCESS = 'mg/REGISTER_SUCCESS';
export const REGISTER_ERROR = 'mg/REGISTER_ERROR';

export const LOAD_CURRENT_USER = 'mg/LOAD_CURRENT_USER';
export const LOAD_CURRENT_USER_SUCCESS = 'mg/LOAD_CURRENT_USER_SUCCESS';
export const LOAD_CURRENT_USER_ERROR = 'mg/LOAD_CURRENT_USER_ERROR';

export const LOAD_USER = 'mg/LOAD_USER';
export const LOAD_USER_SUCCESS = 'mg/LOAD_USER_SUCCESS';
export const LOAD_USER_ERROR = 'mg/LOAD_USER_ERROR';

export const LOAD_USER_SETTINGS = 'mg/LOAD_USER_SETTINGS';
export const LOAD_USER_SETTINGS_SUCCESS = 'mg/LOAD_USER_SETTINGS_SUCCESS';
export const LOAD_USER_SETTINGS_ERROR = 'mg/LOAD_USER_SETTINGS_ERROR';

export const UPDATE_USER = 'mg/UPDATE_USER';
export const UPDATE_USER_SUCCESS = 'mg/UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'mg/UPDATE_USER_ERROR';

export const LOAD_USER_EVENTS = 'mg/LOAD_USER_EVENTS';
export const LOAD_USER_EVENTS_SUCCESS = 'mg/LOAD_USER_EVENTS_SUCCESS';
export const LOAD_USER_EVENTS_ERROR = 'mg/LOAD_USER_EVENTS_ERROR';

export const EVENT_CREATION = 'mg/EVENT_CREATION';
export const EVENT_CREATION_SUCCESS = 'mg/EVENT_CREATION_SUCCESS';
export const EVENT_CREATION_ERROR = 'mg/EVENT_CREATION_ERROR';
